version: '2.1'
services:

  nginx:
    image: nginx:${NGINX_VERSION}
    depends_on:
      - php7.2
    ports:
      - "${NGINX_PORT}:80"
    volumes_from:
      - php7.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled/:/etc/nginx/conf.d/
    networks:
      - webserver
  
  php7.2:
    container_name: webserver_php_7.2
    build:
      context: ./php
      dockerfile: Dockerfile7.2
      args:
        - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
    depends_on:
      - mysql
      - redis
    volumes:
      - ${SITE_DIR}:/var/wwwroot
    networks: 
      - webserver

  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    networks: 
      - webserver

  redis:
    image: redis:${REDIS_VERSION}
    restart: always
    ports:
      - 6379:6379
    networks: 
      - webserver
      
networks:
  webserver: