version: '2.1'
services:

  nginx:
    image: nginx:${NGINX_VERSION}
    depends_on:
      - php7.1
    ports:
      - ${NGINX_PORT}:80
    volumes_from:
      - php7.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled/:/etc/nginx/conf.d/
      - ${NGINX_DATA_DIR}:/data/log
    networks:
      - webserver
  

  php7.1:
    image: mrxia/php:7.1-server
    depends_on:
      - mysql
      - redis
    volumes:
      - ${SITE_DIR}:/var/wwwroot
    networks: 
      - webserver

  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    networks: 
      - webserver

  redis:
    image: redis:${REDIS_VERSION}
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_DATA_DIR}:/data
      - ./redis/etc/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - webserver

networks:
  webserver: