version: '2.1'
services:

  nginx:
    image: nginx:${NGINX_VERSION}
    depends_on:
      - php7.1
    ports:
      - ${NGINX_PORT}:80
    volumes_from:
      - php7.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled/:/etc/nginx/conf.d/
    networks:
      - webserver
  

  php7.1:
    image: mrxia/php:7.1-server
    depends_on:
      - mysql
      - redis
    volumes:
      - /var/wwwroot
    networks: 
      - webserver

  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    networks: 
      - webserver

  redis:
    image: redis:${REDIS_VERSION}
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    networks: 
      - webserver

  bg-sync:
    image: cweagans/bg-sync
    volumes:
      - ${SITE_DIR}:/source
    volumes_from:
      - nginx
    environment:
      - SYNC_DESTINATION=/var/wwwroot
      - SYNC_MAX_INOTIFY_WATCHES=40000
      - SYNC_VERBOSE=1
    privileged: true
    networks: 
      - webserver

networks:
  webserver: