version: '2.1'
services:

  nginx:
    build: ./nginx
    container_name: webserver-nginx
    restart: always
    depends_on:
      - php7.1
    ports:
      - ${NGINX_PORT}:80
      - ${NGINX_PORT_HTTPS}:443
      - ${NGINX_PORT_SSH}:22
    volumes_from:
      - php7.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled/:/etc/nginx/conf.d/
      - ./nginx/cert/:/etc/nginx/cert/
      - ./nginx/stream-enabled/:/etc/nginx/stream-enabled/
      - ${NGINX_LOG_DIR}:/data/log
    networks:
      - webserver
  
  php7.1:
    image: mrxia/php:7.1-server
    container_name: webserver-php
    restart: always
    depends_on:
      - mysql
      - redis
    volumes:
      - ${SITE_DIR}:/var/wwwroot
      - ${PHP_LOG_DIR}:/var/log/php
      - ./php/supervisor/conf.d:/etc/supervisor/conf.d
    networks: 
      - webserver

  mysql:
    build: ./mysql
    container_name: webserver-mysql
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_ONETIME_PASSWORD: 'true'
    volumes:
      - ${MYSQL_DATA_DIR}:/mysql/data
      - ${MYSQL_LOG_DIR}:/mysql/log
      - ${MYSQL_FILES_DIR}:/mysql/files
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/etc/my.cnf:/etc/my.cnf
    networks: 
      - webserver

  redis:
    image: redis:5.0-alpine
    container_name: webserver-redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_DATA_DIR}:/data
      - ./redis/etc/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - webserver

  rabbitmq:
    build: ./rabbitmq
    container_name: webserver-rabbitmq
    restart: always
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_ADMIN_PORT}:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ${RABBIT_DATA_DIR}:/var/lib/rabbitmq
      - ${RABBIT_LOG_DIR}:/var/log/rabbitmq/log
    hostname: ${RABBITMQ_HOSTNAME}
    networks: 
      - webserver

networks:
  webserver: