version: '2.1'
services:

  nginx:
    image: nginx:${NGINX_VERSION}
    depends_on:
      - php5.6
    ports:
      - ${NGINX_PORT}:80
    volumes_from:
      - php5.6
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled/:/etc/nginx/conf.d/
    networks:
      - webserver
  
  php5.6:
    container_name: webserver_php_5.6
    build:
      context: ./php
      dockerfile: Dockerfile5.6
      args:
        - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
    depends_on:
      - mysql
      - redis
    volumes:
      - ${SITE_DIR}:/var/wwwroot
      - ${USER_DIR}:/home/company
    networks: 
      - webserver

  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    networks: 
      - webserver

  redis:
    image: redis:${REDIS_VERSION}
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    networks: 
      - webserver

  postgresql:
    image: postgres:9.6
    restart: always
    ports:
      - ${POSTGTESQL_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGTESQL_ROOT_PASSWORD}
    volumes:
      - ${POSTGTESQL_DATA_DIR}:/var/lib/postgresql
    networks: 
      - webserver

  mongo:
    image: mongo:${MONGO_VERSION}
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    networks: 
      - webserver
      
networks:
  webserver: