version: '2.0'
services:

  nginx:
    image: nginx:1.13.8
    depends_on:
      - php
    ports:
      - "88:80"
    volumes_from:
      - php
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled/:/etc/nginx/conf.d/
    networks:
      - webserver
  
  php:
    build: ./php
    depends_on:
      - mysql
      - redis
    ports:
      - "9000:9000"
      - "9066:9066"
    volumes:
      - E:/wwwroot:/var/wwwroot
    networks: 
      - webserver

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - E:/docker/data/mysql:/var/lib/mysql
    networks: 
      - webserver

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks: 
      - webserver
      
networks:
  webserver: